### PR TITLE
Add priority to supplied item

### PR DESCRIPTION
**Pull request by AxioBen**

### CODE REVIEW

**Comment by fabian** [comment]
@AxioBen Can you rebase this pull request to `master`, so it includes only the relevant commits?

**Comment by AxioBen** [comment]
@fabian To do this one please wait, i had in my branch some dev from @JonathanVanRaemdonck about status.

You should wait his PR for status, do it first, then you can check this PR. 

I will repost a message on this PR when you can check it.

**Comment by AxioBen** [comment]
This one can be reviewed, but we should probably wait an answer to your question on the other PR related to the priority field 
Cf : https://github.com/worldskills/API-Infrastructure-List/pull/11#discussion_r165926405

**Comment by AxioBen** [comment]
@fabian It's ok now, priority is no more a free text field. This one can be reviewed

**Pull request merged**
